Update getting-started.md
Without exposing the variable `book`, the spec `spec/web/controllers/books/create_spec.rb` fails.

```
NoMethodError:         NoMethodError: undefined method 'book' for #<Web::Controllers::Books::Create:0x007ff5e5afbe40>
```

After I applies the changes of the PR the test passed. Am I missing something?